language: python

sudo: required

dist: xenial

python:
  - "3.6"
  - "3.7"

install:
  - pip install -r requirements.txt

script:
  - pytest
  - pytest --cov=starlette_jsonrpc --cov=tests

after_success:
  - codecov